"""Regenerate `subjects.json`, the dashboard's opening fixture.

This is CONSTRUCTED evidence, not a scan. No adapter has run and nothing here
was observed on any real network -- the dashboard labels it as a fixture for
exactly that reason. Its job is to exercise every band and every closure task
so the views can be tested and demonstrated before a sensor exists.

It is generated by code rather than hand-written so it cannot drift out of
shape with the models: every subject below is validated by LedgerSubject on
the way out.

Run:  python tests/fixtures/ledger/build_subjects.py
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from ecdat.model.epistemic import EpistemicState
from ecdat.model.field_value import FieldValue
from ecdat.model.temporal import MigrationEvidence, TemporalEvidence
from ecdat.model.usage_context import CryptoFunction, UsageContext
from ecdat.risk.run import LedgerSubject

OBSERVED = EpistemicState.KNOWN
OUT = Path(__file__).resolve().parent / "subjects.json"


def fn(value, state=OBSERVED, rule_id="FUNC-TLS-KEX-001", refs=("E-probe",)):
    return FieldValue[CryptoFunction](
        value=value,
        state=state,
        evidence_refs=refs if state == OBSERVED else (),
        rule_id=rule_id if value is not None else None,
    )


def alg(value, state=OBSERVED, refs=("E-probe",)):
    return FieldValue[str](
        value=value, state=state, evidence_refs=refs if state == OBSERVED else ()
    )


def when(value, state=OBSERVED, refs=("E-probe",)):
    return FieldValue[date](
        value=value, state=state, evidence_refs=refs if state == OBSERVED else ()
    )


def context(uid, asset, surface, protocol, function, algorithm=None, **kw):
    return UsageContext(
        usage_context_id=uid,
        asset_id=asset,
        surface_id=surface,
        protocol_context=protocol,
        function=function,
        algorithm=algorithm,
        **kw,
    )


def temporal(surface, *, confirmed=None, not_before=None, declared=None):
    return TemporalEvidence(
        surface_id=surface,
        observation_ts=date(2026, 9, 18),
        first_observed=when(confirmed) if confirmed else None,
        not_before=when(not_before, refs=("E-cert",)) if not_before else None,
        declared_go_live=(
            when(declared, state=EpistemicState.DECLARED) if declared else None
        ),
    )


def migration(surface, day, *, group, classical, status=OBSERVED, vantage="dmz-probe-1"):
    return MigrationEvidence(
        surface_id=surface,
        vantage=vantage,
        observed_at=day,
        negotiated_group=group,
        classical_still_accepted=classical,
        status=status,
        evidence_refs=("E-probe",) if status == OBSERVED else (),
    )


SUBJECTS: list[LedgerSubject] = [
    # Long-lived data over a classical key exchange: the headline case.
    LedgerSubject(
        usage_context=context(
            "payments-api:tls:kex",
            "payments-api-key",
            "tls:payments-api:443",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            fn(CryptoFunction.KEY_ESTABLISHMENT),
            alg("X25519"),
        ),
        temporal=temporal("tls:payments-api:443", confirmed=date(2021, 1, 1), not_before=date(2020, 11, 4)),
        binding_key="TEST.X_25Y",
    ),
    # Same shape, short-lived data. Same connection kind, different answer.
    LedgerSubject(
        usage_context=context(
            "session-cache:tls:kex",
            "session-cache-key",
            "tls:session-cache:6379",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            fn(CryptoFunction.KEY_ESTABLISHMENT),
            alg("P-256"),
        ),
        temporal=temporal("tls:session-cache:6379", confirmed=date(2021, 1, 1)),
        binding_key="TEST.X_1Y",
    ),
    # RSA key transport, medium lifetime: SAVABLE centrally, BLEEDING aggressively.
    LedgerSubject(
        usage_context=context(
            "legacy-settlement:tls:kex",
            "legacy-settlement-key",
            "tls:legacy-settlement:443",
            "TLS_RSA_WITH_AES_128_CBC_SHA",
            fn(CryptoFunction.KEY_TRANSPORT, rule_id="FUNC-TLS-KEYTRANSPORT-001"),
            alg("RSA"),
        ),
        temporal=temporal("tls:legacy-settlement:443", confirmed=date(2021, 1, 1)),
        binding_key="TEST.X_7Y",
    ),
    # Migrated, and we watched it happen: the clock stopped at M.
    LedgerSubject(
        usage_context=context(
            "records-api:tls:kex",
            "records-api-key",
            "tls:records-api:443",
            "TLS_AES_256_GCM_SHA384",
            fn(CryptoFunction.KEY_ESTABLISHMENT),
            alg("X25519"),
        ),
        temporal=temporal("tls:records-api:443", confirmed=date(2021, 1, 1)),
        binding_key="TEST.X_25Y",
        migrations=(
            migration(
                "tls:records-api:443",
                date(2026, 6, 1),
                group="X25519MLKEM768",
                classical=False,
            ),
        ),
    ),
    # Configured for hybrid, never observed negotiating it. Still bleeding.
    LedgerSubject(
        usage_context=context(
            "partner-gateway:tls:kex",
            "partner-gateway-key",
            "tls:partner-gateway:443",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            fn(CryptoFunction.KEY_ESTABLISHMENT),
            alg("X25519"),
        ),
        temporal=temporal("tls:partner-gateway:443", confirmed=date(2022, 3, 15)),
        binding_key="TEST.X_25Y",
        migrations=(
            migration(
                "tls:partner-gateway:443",
                date(2026, 5, 1),
                group="X25519MLKEM768",
                classical=False,
                status=EpistemicState.INFERRED,
                vantage="config-file",
            ),
        ),
    ),
    # Certificate on disk, never seen carrying traffic: possible but not confirmed.
    LedgerSubject(
        usage_context=context(
            "archive-node:tls:kex",
            "archive-node-key",
            "tls:archive-node:8443",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            fn(CryptoFunction.KEY_ESTABLISHMENT),
            alg("X25519"),
        ),
        temporal=temporal("tls:archive-node:8443", not_before=date(2019, 3, 1)),
        binding_key="TEST.X_25Y",
    ),
    # Wrap-mode call site: function observed, algorithm from a properties file.
    LedgerSubject(
        usage_context=context(
            "billing-batch:src:KeyWrapService",
            "billing-batch-wrapping-key",
            "src:billing-batch",
            "javax.crypto.Cipher at KeyWrapService.java:27",
            fn(CryptoFunction.KEY_TRANSPORT, rule_id="FUNC-SRC-KEYTRANSPORT-001", refs=("E-semgrep",)),
            alg(None, state=EpistemicState.UNKNOWN),
        ),
        temporal=temporal("src:billing-batch", declared=date(2020, 6, 1)),
        binding_key="TEST.X_10Y",
    ),
    # Offered but never negotiated: capability, not usage.
    LedgerSubject(
        usage_context=context(
            "legacy-settlement:tls:offered",
            "legacy-settlement-cert",
            "tls:legacy-settlement:443",
            "offered, not negotiated: TLS_RSA_WITH_3DES_EDE_CBC_SHA",
            fn(CryptoFunction.KEY_TRANSPORT, state=EpistemicState.INFERRED, rule_id="FUNC-TLS-OFFERED-001"),
            alg("RSA", state=EpistemicState.INFERRED),
        ),
        temporal=temporal("tls:legacy-settlement:443", confirmed=date(2021, 1, 1)),
        binding_key="TEST.X_7Y",
    ),
    # Nothing identifies what this key does.
    LedgerSubject(
        usage_context=context(
            "unknown-appliance:tls:kex",
            "unknown-appliance-key",
            "tls:unknown-appliance:443",
            "TLS_SRP_SHA_WITH_AES_128_CBC_SHA",
            fn(None, state=EpistemicState.UNKNOWN),
        ),
        temporal=temporal("tls:unknown-appliance:443", confirmed=date(2023, 2, 1)),
        binding_key="TEST.X_25Y",
    ),
    # The other clock: a TLS server certificate, session authentication.
    LedgerSubject(
        usage_context=context(
            "payments-api:tls:auth",
            "payments-api-cert",
            "tls:payments-api:443",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 server certificate",
            fn(CryptoFunction.SIGNATURE_AUTH, rule_id="FUNC-CERT-AUTH-001"),
        ),
        temporal=temporal("tls:payments-api:443", confirmed=date(2021, 1, 1)),
        binding_key="TEST.A_SESSION",
    ),
    # The other clock again: a signed artefact that must outlive Z.
    LedgerSubject(
        usage_context=context(
            "firmware-release:signature",
            "firmware-signing-key",
            "artefact:firmware-release",
            "release manifest signature",
            fn(CryptoFunction.SIGNATURE_AUTH, rule_id="FUNC-SRC-SIGNATURE-001", refs=("E-manifest",)),
            alg("RSA"),
        ),
        temporal=temporal("artefact:firmware-release", confirmed=date(2026, 1, 1)),
        binding_key="TEST.A_15Y",
        signed_at=date(2026, 1, 1),
    ),
    # Symmetric bulk encryption: reported, never banded (§5.5 Grover flag).
    LedgerSubject(
        usage_context=context(
            "token-vault:src:TokenVault",
            "token-vault-key",
            "src:token-vault",
            "javax.crypto.Cipher at TokenVault.java:19",
            fn(CryptoFunction.ENCRYPTION, rule_id="FUNC-SRC-KEYTRANSPORT-001", refs=("E-semgrep",)),
            alg("AES/GCM/NoPadding"),
        ),
        temporal=temporal("src:token-vault", declared=date(2022, 1, 1)),
        binding_key="TEST.X_10Y",
    ),
]


def main() -> None:
    document = {
        "schema_version": 1,
        "note": (
            "CONSTRUCTED fixture evidence. No adapter has run and nothing here "
            "was observed on any real network. Regenerate with "
            "tests/fixtures/ledger/build_subjects.py."
        ),
        "subjects": [json.loads(s.model_dump_json()) for s in SUBJECTS],
    }
    OUT.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(SUBJECTS)} subjects)")


if __name__ == "__main__":
    main()
